apiVersion: apps/v1
kind: Deployment
metadata:
  name: razorpage
  labels:
    app: razorpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: razorpage
  template:
    metadata:
      labels:
        app: razorpage
    spec:
      containers:
      - name: razorpage
        image: azuretoolsacr.azurecr.io/razorpage:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

