kind: Service
apiVersion: v1
metadata:
  name: razor-page
  labels:
    app.kubernetes.io/name: 'razor-page'
spec:
  selector:
    app.kubernetes.io/name: razor-page
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
