kind: Service
apiVersion: v1
metadata:
  name: razorpage
  labels:
    app.kubernetes.io/name: 'razorpage'
spec:
  selector:
    app.kubernetes.io/name: razorpage
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
