apiVersion: v1
kind: Service
metadata:
  name: razorpage
  labels: 
    app.kubernetes.io/name: razorpage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: razorpage
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP