kind: Service
apiVersion: v1
metadata:
  name: razorpage
  labels: 
    app: razorpage
spec:
  selector:
    app: razorpage
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
